const FILENAME_MAX_LENGTH = 256;
const CURRENT_VERSION = 1;
const IV_BYTE_LENGTH = 16;
const TAG_BYTE_LENGTH = 16;
const TAG_BIT_LENGTH = TAG_BYTE_LENGTH * 8;
const DEFAULT_BLOCK_SIZE = 64 * 1024;
const BLOCK_OVERHEAD = TAG_BYTE_LENGTH + IV_BYTE_LENGTH;
const DEFAULT_PART_SIZE = 128 * (DEFAULT_BLOCK_SIZE + BLOCK_OVERHEAD);

module.exports = Object.freeze({
  FILENAME_MAX_LENGTH: 256,
  CURRENT_VERSION: 1,
  IV_BYTE_LENGTH: IV_BYTE_LENGTH,
  TAG_BYTE_LENGTH: TAG_BYTE_LENGTH,
  TAG_BIT_LENGTH: TAG_BIT_LENGTH,
  DEFAULT_BLOCK_SIZE: DEFAULT_BLOCK_SIZE,
  BLOCK_OVERHEAD: BLOCK_OVERHEAD,
  DEFAULT_PART_SIZE: DEFAULT_PART_SIZE,
});
